'use client';

import React, { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

import { ReButton } from '@/components/re-ui/ReButton';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';
import { UserRole } from './TransactionsSummaryForProduct';
import { OrderDetails } from '@/types/order';
import { UpdateOrderProgressDTO } from '@/lib/validations/order';
import { updateOrderProgress } from '@/lib/actions/order/order.actions';
import PaymentSuccessful from './PaymentSuccessful';

interface OrderAgreementProps {
  handleCurrentStepChange: (step: number) => void;
  currentStepChange: number;
  showActions?: boolean;
  userRole: UserRole;
  order?: OrderDetails | null;
  loadOrder?: () => Promise<void>;
}

export default function OrderAgreement({
  handleCurrentStepChange,
  currentStepChange,
  showActions = false,
  userRole,
  order,
  loadOrder,
}: OrderAgreementProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [isAgreed, setIsAgreed] = useState(false);
  const [isLoading, setIsLoading] = useState(false); // for Done button

  const handleAcceptOrder = () => {
    if (!isAgreed) return;
    setIsOpen(true);
  };

  const handleConfirmTransaction = async () => {
    setIsLoading(true);
    try {
      const response = await updateOrderProgress(
        {
          status: 'AGREEMENT',
          step: 1,
          notes: 'Agreement signed',
        } as UpdateOrderProgressDTO,
        order?.id as string
      );

      if (response?.success) {
        toast.success('Order agreement accepted successfully!');
        if (loadOrder) await loadOrder();
        handleCurrentStepChange(currentStepChange + 1);

        // slight delay for smooth UX
        setTimeout(() => setIsOpen(false), 500);
      } else {
        toast.error(response?.error || 'Failed to update order progress history');
      }
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : 'Failed to update order progress history'
      );
    } finally {
      setIsLoading(false);
    }
  };

  const handleRejectOrder = () => {
    console.log('Order rejected');
    handleCurrentStepChange(currentStepChange - 1);
  };

  const handleDownload = () => {
    console.log('Downloading escrow agreement PDF');
  };

  // -------------------- SELLER VIEW --------------------
  if (userRole === 'seller' && (order?.status === 'PENDING' || order?.status === 'AGREEMENT')) {
    return (
      <div className="mt-5 rounded-xl border-2 border-gray-200 bg-[#eeeeee] p-5">
        <h2 className="mb-2 font-inter text-lg font-medium">Awaiting Approval</h2>
        <p className="font-inter text-sm text-gray-600">
          Pending confirmation from buyer/seller to agreed-upon descriptions. Await approval for
          transaction to start.
        </p>
      </div>
    );
  }

  // -------------------- BUYER VIEW --------------------
  if (userRole === 'buyer' && (order?.status === 'PENDING' || order?.status === 'AGREEMENT')) {
    return (
      <section className="mt-5 rounded-xl border-2 border-gray-200 bg-[#E6E6E6] p-5">
        {/* Header */}
        <div className="mb-5">
          <h1 className="mb-4 font-inter text-2xl font-semibold text-gray-900">Escrow Agreement</h1>
          <p className="font-inter mb-6 leading-relaxed text-gray-600">
            This agreement confirms that the buyer, {order?.buyer?.firstName}{' '}
            {order?.buyer?.lastName}, has created an escrow transaction for {order?.transactionType}
            . This transaction is governed by an escrow agreement automatically generated by PayAfta
            based on the details provided by both parties. Please review the agreement carefully
            before proceeding.
          </p>
        </div>

        {/* Download PDF */}
        <button
          onClick={handleDownload}
          className="mb-8 flex items-center gap-2 text-blue-600 transition-colors hover:text-blue-700"
        >
          <Download className="h-4 w-4" />
          Download Escrow Agreement (PDF)
        </button>

        {/* Agreement Checkbox */}
        <div className="mb-8 flex items-start gap-3">
          <Checkbox
            id="agreement"
            checked={isAgreed}
            onCheckedChange={(checked) => setIsAgreed(checked as boolean)}
            className="mt-1"
          />
          <label
            htmlFor="agreement"
            className="cursor-pointer text-sm leading-relaxed text-gray-700"
          >
            I have read and agree to the Escrow Agreement. I understand that proceeding confirms my
            acceptance of the terms stated within.
          </label>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col gap-3 sm:flex-row sm:gap-5">
          <Dialog open={isOpen} onOpenChange={setIsOpen}>
            <DialogTrigger asChild>
              <ReButton
                className={`w-full sm:w-2/5 rounded-full ${
                  isAgreed
                    ? 'bg-[#03045B] hover:bg-[#03045B] text-white transition-all'
                    : 'cursor-not-allowed bg-gray-300 text-gray-600'
                }`}
                onClick={handleAcceptOrder}
                disabled={!isAgreed}
              >
                Accept Order
              </ReButton>
            </DialogTrigger>

            <DialogContent className="sm:max-w-[425px]">
              <DialogHeader>
                <DialogTitle>Order Confirmation</DialogTitle>
              </DialogHeader>

              <PaymentSuccessful label="Order Created!" />

              <DialogFooter>
                <ReButton
                  onClick={handleConfirmTransaction}
                  disabled={isLoading}
                  className={`rounded-full flex items-center justify-center gap-2 transition-all duration-300 ${
                    isLoading
                      ? 'cursor-not-allowed bg-gray-300 text-gray-600'
                      : 'bg-[#03045B] hover:bg-[#03045B] text-white'
                  }`}
                >
                  {isLoading ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <span>Processing...</span>
                    </>
                  ) : (
                    'Done'
                  )}
                </ReButton>
              </DialogFooter>
            </DialogContent>
          </Dialog>

          <ReButton
            onClick={handleRejectOrder}
            className="w-full sm:w-2/5 rounded-full border-2 border-[#03045B] bg-white text-[#03045B] hover:bg-gray-50 transition-all duration-300"
          >
            Reject
          </ReButton>
        </div>
      </section>
    );
  }

  // If order is in AGREEMENT status and current step is 1, show completed state
  if (order?.status === 'AGREEMENT' && currentStepChange === 1) {
    return (
      <div className="mt-5 rounded-xl border-2 border-green-200 bg-green-50 p-5">
        <h2 className="mb-2 font-inter text-lg font-medium text-green-800">Agreement Completed</h2>
        <p className="font-inter text-sm text-green-700">
          The escrow agreement has been signed and accepted by both parties. The transaction is now
          ready to proceed to the payment stage.
        </p>
      </div>
    );
  }

  return null;
}
