export const sideNavMenu = [
  {
    id: 1,
    imgBlack: '/assets/admin-dashboard/dashboard/admin-dashboard.svg',
    imgColor: '/assets/admin-dashboard/dashboard/adminDashboardColor.svg',
    name: 'Dashboard',
    alt: '/',
  },
  {
    id: 2,
    imgBlack: '/assets/admin-dashboard/dashboard/users-icon.svg',
    imgColor: '/assets/admin-dashboard/dashboard/usersColorIcon.svg',
    name: 'Users',
    alt: 'users',
  },
  {
    id: 3,
    imgBlack: '/assets/admin-dashboard/dashboard/transcation-icon.svg',
    imgColor: '/assets/admin-dashboard/dashboard/transcationColorIcon.svg',
    name: 'Transaction',
    alt: 'transaction',
  },
  {
    id: 4,
    imgBlack: '/assets/admin-dashboard/dashboard/payment-order-icon.svg',
    imgColor: '/assets/admin-dashboard/dashboard/paymentorderColorIcon.svg',
    name: 'Escrow Orders',
    alt: 'payment-order',
  },
  {
    id: 5,
    imgBlack: '/assets/admin-dashboard/dashboard/payment-order-icon.svg',
    imgColor: '/assets/admin-dashboard/dashboard/paymentorderColorIcon.svg',
    name: 'Fee and Rate',
    alt: 'fee-and-rate',
  },
  {
    id: 6,
    imgBlack: '/assets/admin-dashboard/dashboard/virtual-card-icon.svg',
    imgColor: '/assets/admin-dashboard/dashboard/virtualcardColorIcon.svg',
    name: 'Virtual Card',
    alt: 'virtual-card',
  },
  {
    id: 7,
    imgBlack: '/assets/admin-dashboard/dashboard/team-icon.svg',
    imgColor: '/assets/admin-dashboard/dashboard/teamColorIcon.svg',
    name: 'Team',
    alt: 'team',
  },
  {
    id: 8,
    imgBlack: '/assets/admin-dashboard/dashboard/deliveryPartner.svg',
    imgColor: '/assets/admin-dashboard/dashboard/deliveryPartnerColor.svg',
    name: 'Delivery Partners',
    alt: 'delivery-partners',
  },
  {
    id: 9,
    imgBlack: '/assets/admin-dashboard/dashboard/payment-order-icon.svg',
    imgColor: '/assets/admin-dashboard/dashboard/paymentorderColorIcon.svg',
    name: 'Delivery Data',
    alt: 'delivery-data',
  },
  {
    id: 10,
    imgBlack: '/assets/admin-dashboard/dashboard/notificationIcon.svg',
    imgColor: '/assets/admin-dashboard/dashboard/notificationColorIcon.svg',
    name: 'Notification',
    alt: 'notification',
  },
  {
    id: 11,
    imgBlack: '/assets/admin-dashboard/dashboard/rider-icon.svg',
    imgColor: '/assets/admin-dashboard/dashboard/riderColorIcon.svg',
    name: 'Rider',
    alt: 'rider',
  },
  {
    id: 12,
    imgBlack: '/assets/admin-dashboard/dashboard/settings.svg',
    imgColor: '/assets/admin-dashboard/dashboard/settings.svg',
    name: 'Settings',
    alt: 'setting',
  },
];
