export const sideNavMenu = [
  {
    id: 1,
    imgBlack: '/assets/dashboard/Dashboard/dashboard.svg',
    imgColor: '/assets/dashboard/Dashboard/dashboardColorIcon.svg',
    name: 'Dashboard',
    alt: '/',
    root: 'dashboard',
  },
  {
    id: 2,
    imgBlack: '/assets/dashboard/Dashboard/walletIcon.svg',
    imgColor: '/assets/dashboard/Dashboard/walletColorIcon.svg',
    name: 'Wallets',
    alt: 'wallets',
  },
  {
    id: 3,
    imgBlack: '/assets/dashboard/Dashboard/payment-order.svg',
    imgColor: '/assets/dashboard/Dashboard/payment-order.svg',
    name: 'Orders',
    isChildrean: true,
    newOrder: {
      id: 1,
      name: 'New Order',
      alt: 'new-order',
    },
    viewOrder: {
      id: 2,
      name: 'View Orders',
      alt: 'track-links',
    },
  },
  {
    id: 4,
    imgBlack: '/assets/dashboard/Dashboard/deliveryIcon.svg',
    imgColor: '/assets/dashboard/Dashboard/deliveryColorIcon.svg',
    name: 'Delivery',
    alt: 'delivery',
  },
  {
    id: 4,
    imgBlack: '/assets/dashboard/Dashboard/referral-icon.svg',
    imgColor: '/assets/dashboard/Dashboard/referral-icon.svg',
    name: 'Add Referral',
    alt: 'add-referral',
  },
  {
    id: 5,
    imgBlack: '/assets/dashboard/Dashboard/chat.svg',
    imgColor: '/assets/dashboard/Dashboard/chatColorIcon.svg',
    name: 'Chats',
    alt: 'chats',
  },
  // {
  //   id: 6,
  //   imgBlack: '/assets/dashboard/Dashboard/virtual-card.svg',
  //   imgColor: '/assets/dashboard/Dashboard/virtual-card.svg',
  //   name: 'Virtual Card',
  //   alt: 'virtual-card',
  // },
  {
    id: 6,
    imgBlack: '/assets/dashboard/Dashboard/settings.svg',
    imgColor: '/assets/dashboard/Dashboard/settingColorIcons.svg',
    name: 'Settings',
    alt: 'settings',
  },
  {
    id: 7,
    imgBlack: '/assets/dashboard/Dashboard/support.svg',
    imgColor: '/assets/dashboard/Dashboard/supportColorIcon.svg',
    name: 'Support',
    alt: 'support',
  },
];
