export const sideNavMenu = [
  {
    id: 1,
    imgBlack: '/assets/dashboard/Dashboard/dashboard.svg',
    imgColor: '/assets/dashboard/Dashboard/dashboard.svg',
    name: 'Dashboard',
    alt: '/',
  },
  {
    id: 2,
    imgBlack: '/assets/dashboard/Dashboard/transactions.svg',
    imgColor: '/assets/dashboard/Dashboard/transactions.svg',
    name: 'Transactions',
    alt: 'transactions',
  },
  {
    id: 3,
    imgBlack: '/assets/dashboard/Dashboard/payment-order.svg',
    imgColor: '/assets/dashboard/Dashboard/payment-order.svg',
    name: 'Track Links',
    alt: 'track-links',
  },
  {
    id: 4,
    imgBlack: '/assets/dashboard/Dashboard/chat.svg',
    imgColor: '/assets/dashboard/Dashboard/chat.svg',
    name: 'Chats',
    alt: 'chats',
  },
  {
    id: 5,
    imgBlack: '/assets/dashboard/Dashboard/virtual-card.svg',
    imgColor: '/assets/dashboard/Dashboard/virtual-card.svg',
    name: 'Virtual Card',
    alt: 'virtual-card',
  },
  {
    id: 6,
    imgBlack: '/assets/dashboard/Dashboard/settings.svg',
    imgColor: '/assets/dashboard/Dashboard/settings.svg',
    name: 'Settings',
    alt: 'settings',
  },
  {
    id: 7,
    imgBlack: '/assets/dashboard/Dashboard/support.svg',
    imgColor: '/assets/dashboard/Dashboard/support.svg',
    name: 'Support',
    alt: 'support',
  },
];
